// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AlgoliaSearchBox: typeof import('./theme/components/AlgoliaSearchBox.vue')['default']
    ArrowLeft: typeof import('./theme/components/icons/ArrowLeft.vue')['default']
    ArrowRight: typeof import('./theme/components/icons/ArrowRight.vue')['default']
    BuySellAds: typeof import('./theme/components/BuySellAds.vue')['default']
    CarbonAds: typeof import('./theme/components/CarbonAds.vue')['default']
    Demo: typeof import('./theme/components/Demo.vue')['default']
    EditLink: typeof import('./theme/components/EditLink.vue')['default']
    Home: typeof import('./theme/components/Home.vue')['default']
    HomeFeatures: typeof import('./theme/components/HomeFeatures.vue')['default']
    HomeFooter: typeof import('./theme/components/HomeFooter.vue')['default']
    HomeHero: typeof import('./theme/components/HomeHero.vue')['default']
    LastUpdated: typeof import('./theme/components/LastUpdated.vue')['default']
    NavBar: typeof import('./theme/components/NavBar.vue')['default']
    NavBarTitle: typeof import('./theme/components/NavBarTitle.vue')['default']
    NavDropdownLink: typeof import('./theme/components/NavDropdownLink.vue')['default']
    NavDropdownLinkItem: typeof import('./theme/components/NavDropdownLinkItem.vue')['default']
    NavLink: typeof import('./theme/components/NavLink.vue')['default']
    NavLinks: typeof import('./theme/components/NavLinks.vue')['default']
    NextAndPrevLinks: typeof import('./theme/components/NextAndPrevLinks.vue')['default']
    OutboundLink: typeof import('./theme/components/icons/OutboundLink.vue')['default']
    Page: typeof import('./theme/components/Page.vue')['default']
    PageFooter: typeof import('./theme/components/PageFooter.vue')['default']
    SideBar: typeof import('./theme/components/SideBar.vue')['default']
    SideBarLinks: typeof import('./theme/components/SideBarLinks.vue')['default']
    ToggleSideBarButton: typeof import('./theme/components/ToggleSideBarButton.vue')['default']
  }
}

export { }
