# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main
      - dev
      - next

  pull_request:
    branches:
      - main
      - dev
      - next

jobs:     
  deploy:
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v2
        - name: Install yarn
          run: yarn
          
        - uses: actions/checkout@v2
        - name: docs:build
          run: npm run docs:build
          
        - name: GitHub Pages v3
          uses: peaceiris/actions-github-pages@v3.1.12
          with:
           publish_dir: ./packages


