# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - main
      - dev
      - next

  pull_request:
    branches:
      - main
      - dev
      - next

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          
      - name: Install yarn
      - run: yarn
      
      - name: docs:build
      - run: npm run docs:build
      
      - name: docs:serve
      - run: npm run docs:serve
      
  deploy:
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v2
        - name: Deploy
          with:
           publish_dir: ./packages

